project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "RRP'24"
  description: "Reproducible Research Practices course"
  site-url: "https://cgranell.github.io/rrp"
  repo-url: "https://www.github.com/cgranell/rrp"
  reader-mode: true

  page-footer:
    left: "[cgranell.github.io/rrp](https://cgranell.github.io/rrp)"
    right:
    - text: "License"
      href: LICENSE.md
    - text: "Code of Conduct"
      href: CODE_OF_CONDUCT.md

  navbar:
    logo: "images/ESCOLA-DOCTORAT-es-blanco.png"
    logo-alt: "Escola de Doctorat, UJI"
    logo-href: https://www.uji.es/estudis/centres/escola-doctorat/base/info-general/escola/


    left:
      - href: index.qmd
        text: Overview
      - href: hello.qmd
        text: "Hello!"
      - href: intro.qmd
        text: "1 Intro"
      - href: assessment.qmd
        text: "2 Assessment"
      - href: practices.qmd
        text: "3 Practices"
      - href: uji.qmd
        text: "4 UJI"
      - href: extras.qmd
        text: "Extras"

    right:
      - href: https://reproducible-agile.github.io/
        text: "Reproducible Research @ AGILE"
      - icon: github
        href: https://www.github.com/cgranell/rrp

  sidebar:
    - id: hello
      title: "Hello!"
      style: "docked"
      align: left
      contents:
        - href: hello.qmd
        - href: materials/00-personas.qmd
        - href: materials/00-units.qmd
        - href: materials/00-tech-stack.qmd

    - id: intro
      title: "Intro"
      style: "docked"
      align: left
      contents:
        - href: intro.qmd
          text: "Intro R&R"
        - href: materials/01-historical-notes.qmd
        - href: materials/01-concept.qmd
        - href: materials/01-comparison.qmd
        - href: materials/01-across-disciplines.qmd

    - id: assessment
      title: "Reproducibility assessment"
      contents:
        - href: assessment.qmd


    - id: practices
      title: "Recommendations and practices"
      contents:
        - href: practices.qmd


    - id: UJI
      title: "UJI context"
      contents:
        - href: uji.qmd

    - id: extras
      title: "Additional materials"
      contents:
        - href: extras.qmd
        - href: materials/05-glossary.qmd
        - href: materials/05-references.qmd
        - href: materials/05-key-people.qmd

format:
  html:
    theme:
      light: minty
      dark: darkly
    toc: true

bibliography: references.bib
citations-hover: true
citation-location: document

