project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "RRP'24"
  description: "Reproducible Research Practices course"
  site-url: "https://cgranell.github.io/rrp"
  repo-url: "https://www.github.com/cgranell/rrp"

  page-footer:
    left: "[cgranell.github.io/rrp](https://cgranell.github.io/rrp)"
    right:
    - text: "License"
      href: LICENSE.md
    - text: "Code of Conduct"
      href: CODE_OF_CONDUCT.md

  navbar:
    logo: "images/ESCOLA-DOCTORAT-es-blanco.png"
    logo-href: https://www.uji.es/estudis/centres/escola-doctorat/base/info-general/escola/


    left:
      - href: index.qmd
        text: Overview
      - href: intro.qmd
        text: "Intro"
      - href: recommendations.qmd
        text: "Recommendations"
      - href: extras.qmd
        text: "Extras"

    right:
      - href: https://reproducible-agile.github.io/
        text: "Reproducible Research @ AGILE"
      - icon: github
        href: https://www.github.com/cgranell/rrp

  sidebar:
    - id: intro
      title: "Intro"
      style: "docked"
      align: left
      contents:
        - href: intro.qmd
          text: "Intro R&R"
        - href: materials/01-historical-notes.qmd
        - href: materials/01-concept.qmd

    - id: recommendations
      title: "Recommendations and practices"
      contents:
        - href: recommendations.qmd


    - id: extras
      title: "Additional materials"
      contents:
        - href: extras.qmd
        - href: materials/03-glossary.qmd
        - href: materials/03-references.qmd

format:
  html:
    theme: minty
    toc: true

bibliography: references.bib
citations-hover: true
citation-location: document

