---
title: "Learner persona"
---

## Who is this course for?

There are many answers to this question, depending on your needs, prior skills, and motivation to adopt the *right way* of doing science 😀.

Like you, a *Learner Persona* [@wilson2019] consists of:

-   a general background,
-   what you already know,
-   what you want to know, and
-   other special needs you may have.

If you are working on your doctoral thesis, do you identify better with [Celine](#celine) or with [Víctor](#victor)? If you are an experienced researcher, do you identify with [Juan](#juan)'s or [Ada](#ada)'s perspective on reproducibility? If teaching is your top priory, do your learning needs fit with [Ana](#ana)'s or [Luis](#luis)'?

### Celine {#celine}

Celine has a degree in psychology from England and has just enrolled in the UJI doctoral school. Her doctoral thesis deals with the application of new technologies to improve behavioural therapies for patients diagnosed with gambling addiction.

Celine plans to carry out several experiments with patients during her doctoral period. She knows some tools for data analysis (such as SPSS) from her bachelor's degree, but she has never taken a formal programming course, although she has thought about it often. She sometimes thinks that she suffers from the [impostor syndrome](https://en.wikipedia.org/wiki/Impostor_syndrome) as soon as she faces with programming languages or advanced data analytical tools.

Celine would like to systematize the data analysis of the experiments that she will be conducting in her doctoral project. Yet, above all, she wants to prove to herself that she can learn computational competences. The terms reproducibility and replicability sound familiar to her and she thinks that they can be useful to speed up the tedious work of her experiments, but she does not know where to start.

### Víctor {#victor}

Víctor studied a chemistry degree at UJI and is in the final phase of his PhD thesis on computational chemistry, which he hopes to defend once he completes a planned research stay in France.

Víctor learned R early in his thesis period and it is still the programming language in his research. Like in many other tools, he was self-taught in the use of Github and uses it to version his own software and to collaborate with other colleagues. He has published some relevant articles in which the developed software has been a main contribution.

Víctor wants to improve his skills and expand his knowledge about reproducible workflows. The best academic journals in his field now require that every submission come with code and data, and he knows that an article published in those high-profile journals can open the door to a postdoc job.

### Juan {#juan}

Juan is a professor of Economics at the UJI. He has four six-year research periods and a good record of scientific publications. He is responsible for a quantitative economics course which in turn is the focus of his research.

Juan is surprised by the current hype about the *reproducibility crisis* that he reads about in Science and Nature editorials. He considers that crisis an exaggeration, like so many other buzzwords that he has witnessed in his long academic career. He has never needed reproducibility to have a successful academic career.

Despite this, Juan wants to make sure that his beliefs about reproducibility and reproducible practices are well founded.

### Ada {#ada}

Ada is doing her first postdoc in Germany. She holds a PhD in aeronautics from the Caltech and Bachelor degree in mechanical engineering from UJI. Her research interests include computational fluid dynamics, high-performance computing, and computational biophysics. 

Since the beginning of his doctoral period, Ada has been using R and Python, but wants to modernize his skills to cover other facets of reproducible research beyond coding. She regularly uses open source tools and would love to become an advocate for open source software for science and education. 

Ada wants to delve deeper into the principles and practices of reproducible research to have a holistic view and spread the importance of adopting reproducible practices among other colleagues in her field of research.


### Ana {#ana}

Ana is a professor of Computer Science at the UJI. She hardly never investigates, but she is very active and is concerned with improving her teaching practices. She is responsible for an introductory programming course for large groups of freshmen.

Ana is up to date with teaching innovations and everything related to educational technology. For a decade, she has been applying the most recent learning methodologies and innovative techniques in her classes with considerable success, according to what her students say in surveys.

Ana wants to know if reproducibility and teaching combine in some way, since reproducibility and research always go hand in hand in everything she has read. She is wondering how to bring reproducibility aspects into her practical sessions, such as in peer assessment and peer instructions, and even for the creation of teaching materials. She is interested in guides and practical examples to get inspired to improving her teaching materials and practical classes.

### Luis {#luis}

Luis is a professor at the Department of Philosophy and Sociology at UJI. He graduated in History and received a doctorate in Moral Philosophy.

He has written several books in his discipline, as is common practice in his monograph-dominated discipline. Additionally, he is director of an academic journal that has recently been indexed in national and international databases.

Luis wonders if open science, FAIR principles, and reproducible research can play a role in his full-length monograph-based research practices and how they can be integrated, if possible, into his teaching. Luis is also interested in capturing some new ideas for his academic journal.